### ISSUE TITLE
Current price label

### ISSUE THREAD

**Issue by myarmolik** [gellerda/FancyCandles#10]
I would like to see in your FancyCandles library a label on the chart that would show the current price

![image](https://user-images.githubusercontent.com/73881887/117166186-d1d1fc00-adce-11eb-862e-27fde2c8b630.png)

Thanks for the library

**Comment by Johnny183** [comment]
Would also like to see this

**Comment by gellerda** [comment]
Done!
Look at the IsCurrentPriceLabelVisible, CurrentPriceLabelBackground and CurrentPriceLabelForeground properties.
