### ISSUE TITLE
  <local:ObservableOverlayIndicatorCollection> error

### ISSUE THREAD

**Issue by Succubussix** [gellerda/FancyCandles#15]
everything is working but not that line it says not exist.. i already added this 

```
     xmlns:fc="clr-namespace:FancyCandles;assembly=FancyCandles"
        xmlns:fci="clr-namespace:FancyCandles.Indicators;assembly=FancyCandles"   
  ```
  and it works without that line.. what is that line for?

**Comment by Succubussix** [comment]
also binance have this 

```
       //t,O,H,L,C,v
            /*
             * 
             * 
             * {
   "e": "kline",
   "E": 1621683817418,
   "s": "ETHUSDT",
   "k": {
     "t": 1621683000000,
     "T": 1621683899999,
     "s": "ETHUSDT",
     "i": "15m",
     "f": 442253228,
     "L": 442280109,
     "o": "2428.17000000",
     "c": "2413.16000000",
     "h": "2444.58000000",
     "l": "2392.89000000",
     "v": "16408.62746000",
     "n": 26882,
     "x": false,
     "q": "39562225.33133950",
     "V": "7644.34255000",
     "Q": "18434479.06643740",
     "B": "0"
   }
 }
 ```
 
 the v value is not long.. it shows error if i pass that

**Comment by gellerda** [comment]
> everything is working but not that line it says not exist.. i already added this
> 
> ```
>      xmlns:fc="clr-namespace:FancyCandles;assembly=FancyCandles"
>         xmlns:fci="clr-namespace:FancyCandles.Indicators;assembly=FancyCandles"   
> ```
> 
> and it works without that line.. what is that line for?

It is namespace declaration. It can not work without it. For example, if you want to use the CandleChart element, which is defined in the FancyCandles namespace, in your XAML code, you must declare the FancyCandles namespace.

Namespace declaration:
xmlns:fc="clr-namespace:FancyCandles;assembly=FancyCandles"
...
Using an element from the aforementioned namespace:
<fc:CandleChart .../>
