### ISSUE TITLE
Is it possible to draw a 1 sec chart?

### ISSUE THREAD

**Issue by azhali** [gellerda/FancyCandles#16]
Hi, 

First of all great work on control. 

I have few questions which I would be appreciate if someone can help me with.

- I would like to draw a second chart of BTCUSD but when I do that, it only shows Y-Axis and Price but no time on the X-Axis. Chart draws and work but missing labels on the X-Axis. 
- Is it possible to move the Price label box inside the chart? Currently its showing outside the bounds of the chart.
- OHLC values are double but when they show on the chart, they are not formatted and showing as many decimal points. Is there a way to fix that?
- Is it possible to add a line or image at certial point on the chart at runtime based on custom logic?

Please see screenshot for reference.

![image](https://user-images.githubusercontent.com/6758314/120666020-288d2d00-c484-11eb-906a-37d1881921d3.png)

Regards
Azhar

**Comment by gellerda** [comment]
Hello.
I will do it in the nearest future.

**Comment by gellerda** [comment]
Hello.
Could you give me the XAML code of this window? I can't recreate a situation when the grey tip box is positioned outside of the chart like on your picture.

**Comment by gellerda** [comment]
I have found a solution of incorrect popup, tips and context menu location problem. See MainWindow.xaml.cs files in example projects.
