### ISSUE TITLE
Missing FancyPrimitives project

### ISSUE THREAD

**Issue by ehaddan** [gellerda/FancyCandles#17]
I downloaded the solution and the FancyPrimitives project seems to be missing.

**Comment by gellerda** [comment]
FancyPrimitives is a separate independent project and located in its own separate repository.
You have to clone the FancyPrimitives repo to the same root directory as FancyCandles:
-SomeRootFolder
--FancyCandles
--FancyPrimitives

**Comment by ehaddan** [comment]
Thank you!
