### ISSUE TITLE
Вертикальный скролинг ?

### ISSUE THREAD

**Issue by TheHomer7** [gellerda/FancyCandles#18]
Привет, не знаю понимаешь ли ты русский язык.

Мне бы хотелось узнать возможен ли вертикальный скролинг ? В какую сторону мне копать дабы это реализовать самому ? Я не прошу реализовать такой функционал, мне нужно понять возможно ли это и куда копать в коде.

**Comment by gellerda** [comment]
Привет.
Вертикальный скроллинг где? Я не совсем понимаю для чего он нужен. График же вмещает по высоте все свечки, отображенные на данный момент. Для графика можно изменить верхний и нижний отступ от края области. Например, как где, в каком терминале или веб-сервисе?

**Comment by gellerda** [comment]
Ну т.е. зачем тебе сколить вверх или вниз, там же ничего нет?

**Comment by TheHomer7** [comment]
https://ru.tradingview.com/chart/?symbol=MOEX:USDRUB_TOM&source=unauth_header&feature=launch_chart Вот к примеру, если нажать ЛКМ на ось цен,  то можно масштабировать цену и сузить график, а так же скролить вверх/вниз. Зачем мне это ? Я занимаюсь разработкой скальперского привода, и трейдерам это нужно, зачем не знаю но нужно. Вот и хотелось бы такое реализовать в новых графиках.

**Comment by TheHomer7** [comment]
И все что я смог пока что придумать это работать с CandleExtremums, но это даст сжатие графика по вертикали, но скроллинг я пока что не придумал. Ну и за ранее спасибо за помощь

**Comment by TheHomer7** [comment]
Если есть такая возможность, можешь отписать в VK https://vk.com/gametime_homer, чисто для удобства общения и тд, так как совет разработчика либы не помешал бы)

**Comment by gellerda** [comment]
Ну так это и есть изменение этих полей PriceChartBottomMargin и PriceChartTopMargin. В нестройках они находятся на вкладке Price Chart/ "Indent from top" и "Indent from bottom". Но там я их ограничил неотрицательными значениями т.к. не думал что отрицательные значения могут понадобиться. А если менять эти свойства через API то нет ограничений. Правда я не тестил что будет при отрицательных значениях. Ну и скроллинг вертикальный прикрутить нужно если значения отрицательными становятся. ОК отпишу в VK.

**Comment by TheHomer7** [comment]
хммм, а это скорее всего будет работать

**Comment by gellerda** [comment]
Не, скорее всего все сломается :)
Да и вертикальный скроллинг глаза мозолить будет.
Я отписал в вк. Обращайся, если что.

**Comment by TheHomer7** [comment]
Если сломается починю, и так под себя многое переделывать придется, обязательно что-то сломается. Все же вертикальный скролинг и сжимание нужно скорее всего для анализа, чем для торговли.
