### ISSUE TITLE
Price Ticker Does not showing negative value,

### ISSUE THREAD

**Issue by BharaniGdharan** [gellerda/FancyCandles#19]
![FancyCandleNoNegative](https://user-images.githubusercontent.com/3683064/125412024-25b71d80-e3dc-11eb-8c1c-bca021478378.PNG)
![PriceTicker](https://user-images.githubusercontent.com/3683064/125412081-32d40c80-e3dc-11eb-8af2-30b0e7a6e1cc.PNG)

Price Ticker Does not showing negative value,
For a research purpose I'm using candle chart,
It can contains Negative Value,
Where to fix It !
Thank you in Advance.

**Comment by gellerda** [comment]
Done! 
I have fixed it and added a new button to test candles with negative values. Check it out.

**Comment by BharaniGdharan** [comment]
Thank You,
Negative value it is fixed and Working like a Charm.
But after disabling the Volume Histogram the reference is getting invisible at the bottom of chart.
![Invisible Value](https://user-images.githubusercontent.com/3683064/125948956-9b83bbf3-dfc6-4200-8e67-be62d72d3097.PNG)

**Comment by gellerda** [comment]
Fixed! 
Thank you for your bug reports!

**Comment by BharaniGdharan** [comment]
Its Done,
Thank you,
For your wonderful support !
